app/drift/models.py
from sqlalchemy import Column, Integer, String, SmallInteger

from app import Model
from app.libs.enums import PendingStatus


class Drift(Model):
    """
        一次具体的交易信息
    """
    id = Column(Integer, primary_key=True)

    # 邮寄信息
    recipient_name = Column(String(20), nullable=False)
    address = Column(String(100), nullable=False)
    message = Column(String(200))
    mobile = Column(String(20), nullable=False)

    # 书籍信息
    isbn = Column(String(13))
    book_title = Column(String(50))
    book_author = Column(String(30))
    book_img = Column(String(50))

    # 请求者信息
    requester_id = Column(Integer)
    requester_nickname = Column(String(20))
    # 十一月

    # 赠送者信息
    contributor_id = Column(Integer)
    gift_id = Column(Integer)
    contributor_nickname = Column(String(20))

    _pending = Column('pending', SmallInteger, default=1)

    @property
    def pending(self):
        return PendingStatus(self._pending)

    @pending.setter
    def pending(self, status):
        self._pending = status.value

app/drift/forms.py
from wtforms import Form
from wtforms import StringField
from wtforms.validators import Length, DataRequired, Regexp


class DriftForm(Form):
    recipient_name = StringField(validators=[
        DataRequired(),
        Length(
            min=2, max=20,
            message='收件人姓名长度必须在2到20个字符之间')
    ])
    mobile = StringField(validators=[
        DataRequired(),
        Regexp("^(13[0-9]|14[579]|15[0-3,5-9]|16[6]|17[0135678]|18[0-9]|19[89])\\d{8}$", 0, '请输入正确的手机号')
    ])
    message = StringField()
    address = StringField(validators=[
        DataRequired(),
        Length(min=10, max=70,
               message='地址还不到10个字吗？尽量写详细一些吧')
    ])

app/drift/__init__.py
from flask import Blueprint

drift = Blueprint('drift', __name__, url_prefix='/drift', template_folder='templates')

from . import views
from . import models

app/drift/views.py
from flask import flash, redirect, url_for, render_template, request
from flask_login import login_required, current_user
from sqlalchemy import or_, desc

from app import db
from app.book.viewmodels import Book
from app.libs.email import send_mail
from app.libs.enums import PendingStatus
from app.mian.models import Gift, Wish
from . import drift as app
from .forms import DriftForm
from .viewmodels import Drifts
from .models import Drift


@app.route('/<int:drift_id>/redraw')
@login_required
def redraw_drift(drift_id):
    with db.auto_commit():
        drift = Drift.query.filter_by(id=drift_id,
                                      requester_id=current_user.id).first_or_404()
        drift.pending = PendingStatus.Redraw
        current_user.beans += 1
        drift.delete()
    return redirect(url_for('drift.pending'))


@app.route('/<int:drift_id>/reject')
@login_required
def reject_drift(drift_id):
    from app.auth.models import User
    with db.auto_commit():
        drift = Drift.query.filter(Drift.id == drift_id,
                                   Gift.user_id == current_user.id).first_or_404()
        drift.pending = PendingStatus.Reject
        requester = User.query.get_or_404(drift.requester_id)
        requester.beans += 1
    return redirect(url_for('drift.pending'))


@app.route('/<int:drift_id>/mailed')
@login_required
def mailed_drift(drift_id):
    with db.auto_commit():
        drift = Drift.query.filter_by(id=drift_id,
                                      contributor_id=current_user.id).first_or_404()
        drift.pending = PendingStatus.Success
        current_user.beans += 1
        Gift.query.filter_by(id=drift.gift_id).update(
            {Gift.is_launched: True}
        )
        Wish.query.filter_by(isbn=drift.isbn,
                             user_id=drift.requester_id,
                             is_launched=False).update(
            {Wish.is_launched: True}
        )
    return redirect(url_for('drift.pending'))


@app.route('/<int:gift_id>', methods=['GET', 'POST'])
@login_required
def send_drift(gift_id):
    gift = Gift.query.get_or_404(gift_id)
    if gift.is_yourself_gift(current_user.id):
        flash("这本书是你自己的(^-^), 不能向自己索要书籍奥")
        return redirect(url_for('book.detail', isbn=gift.isbn))
    can = current_user.can_send_drift()
    if not can:
        return render_template('not_enough_beans.html', beans=current_user.beans)
    form = DriftForm(request.form)
    if request.method == 'POST' and form.validate():
        save_drift(form, gift)
        send_mail(gift.user.email, '有人想要一本书', 'email/get_gift', wisher=current_user, gift=gift)
        return redirect(url_for('drift.pending'))
    contributor = gift.user.summary
    return render_template('drift/drift.html', contributor=contributor, user_beans=current_user.beans, form=form)


@app.route('/pending')
@login_required
def pending():
    drifts = (Drift
              .query
              .filter(or_(Drift.requester_id == current_user.id,
                          Drift.contributor_id == current_user.id))
              .order_by(desc(Drift.create_time))
              .all())
    drifts = Drifts(drifts, current_user.id).data

    return render_template('drift/pending.html', drifts=drifts)


def save_drift(form, gift):
    with db.auto_commit():
        drift = Drift()
        form.populate_obj(drift)

        drift.gift_id = gift.id
        drift.requester_id = current_user.id
        drift.requester_nickname = current_user.nickname
        drift.contributor_nickname = gift.user.nickname
        drift.contributor_id = gift.user.id

        book = Book(gift.book)
        drift.book_title = book.title
        drift.book_author = book.author
        drift.book_img = book.image
        drift.isbn = book.isbn

        current_user.beans -= 1
        db.session.add(drift)

app/drift/templates/drift/drift.html
{% extends "base.html" %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/drift.css')}}">
{% endblock %}
{% block navbar %}
{% endblock %}
{% block content %}
    <div style="margin-top:100px;" class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="row">
                <div class="col-md-2">
                    <a id='nav_url' href="{{ url_for('main.index') }}">去首页</a>
                </div>
            </div>
            <div class="bg-container">
                <div class="row">
                    <div class="col-md-12 text-center bg-head">
                        <span class="drift-title">向<span
                                class="space">{{ contributor.nickname }}</span>请求这本书</span>
                    </div>
                </div>
                <div style="margin-top:15px;" class="row">
                    <div class="col-md-10 col-md-offset-1 flex-vertical gifter-container">
                        <span class="sub-title-color">以下是书籍拥有者信息，诚信度供你参考:</span>
                        <span style="margin-top:10px; margin-bottom:10px;">{{ contributor.nickname }}</span>
                        <div><span
                                class="description-font">鱼豆：</span><span>{{ contributor.beans }}</span>
                        </div>
                        <div><span
                                class="description-font">接受/送出书籍：</span><span>{{ contributor.contrib_receive }}</span>
                        </div>
                    </div>
                </div>
                <div style="margin-top:10px;" class="row">
                    <div class="col-md-10 col-md-offset-1">
                        <span class="main-color">本次交易将消耗你1个鱼豆，你当前还有{{ user_beans }}个鱼豆</span>
                    </div>
                </div>
                <form action="" method="post">
                    <div style="margin-top:20px;" class="row">
                        <div class="col-md-10 col-md-offset-1 flex-vertical input-margin">
                            <label class="sub-title-color" for="recipient_name">收件人姓名</label>
                            <div class="row">
                                <div class="col-md-5">
                                    <input placeholder="请填写收件人姓名" id="recipient_name"
                                           name="recipient_name"
                                           class="normal-input btn-block form-control"
                                           value="{{ form.recipient_name.data | default('', true) }}">
                                </div>
                            </div>
                            <label class="sub-title-color" for="mobile">联系电话</label>
                            <div class="row">
                                <div class="col-md-5">
                                    <input placeholder="如13818181818" id="mobile"
                                           name="mobile"
                                           class="normal-input btn-block form-control"
                                           value="{{ form.mobile.data | default('', true) }}">
                                </div>
                            </div>
                            <label class="sub-title-color" for="address">书籍收件地址</label>
                    <textarea class="form-control" rows="3" id="address" name="address"
                              placeholder="如，张三 北京市清华大学666室。请务必确保该地址能够收到书籍">{{ form.address.data | default('',true) }}</textarea>
                            <label class="sub-title-color" for="message">对他 / 她
                                说的话</label>
                        <textarea class="form-control" id="message" name="message"
                                  rows="4"
                                  placeholder="如有一些特别的要求，可以在这里填写">{{ form.message.data | default('',true) }}</textarea>
                        </div>
                    </div>
                    <div class="row">
                        <div style="position: relative;left:-20px;"
                             class="col-md-5 col-md-offset-4 flex-vertical text-center">
                            <input style="margin-top:12px;" type="submit"
                                   class="btn btn-big btn-block" value="提交">
                        <span style="margin-top:15px;"
                              class="main-color">提交信息，等待{{ contributor.nickname }}将书籍邮寄给你</span>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script src="{{ url_for('static', filename='3rd/jquery-3.2.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/drift.js') }}"></script>
{% endblock %}

app/drift/templates/drift/pending.html
{% extends "base.html" %}
{% block head %}
    {{ super() }}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/pending.css')}}">
{% endblock %}
{% block content %}
    <div class="row module-title">
        <div style="margin-top:30px;" class="col-md-2">
            <span class='sub-title'>鱼漂记录</span>
        </div>
    </div>
    {% if not drifts %}
    暂无鱼漂记录
    {% else %}
    {% for drift in drifts %}
        <div style="margin-top:20px;" class="row drift-container">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-2">
                        <img class="book-img-small shadow" src="{{ drift.book_img }}">
                    </div>
                    <div style="margin-left:-30px;"
                         class="col-md-8 flex-vertical description">
                        <div><span>书籍名：</span><span>{{ drift.book_title }}</span></div>
                        <div><span>作者：</span><span>{{ drift.book_author }}</span></div>
                        <div><span>发起日期：</span><span>{{ drift.date }}</span></div>
                        <div>
                            {% if drift.you_are == 'requester' %}
                                <span>向他请求：</span>
                            {% else %}
                                <span>请求者：</span>
                            {% endif %}
                            <span>{{ drift.operator }}</span>
                        </div>
                        <div><span>状态：</span><span
                                class="status-color">{{ drift.status_str }}</span></div>
                        <div><span>邮寄地址：</span><span
                                class="space">{{ drift.recipient_name }}</span><span>{{ drift.address }}</span>
                        </div>
                        <div><span>联系电话：</span><span>{{ drift.mobile }}</span></div>
                    </div>
                    <div class="col-md-2 flex-vertical">
                        {% if drift.you_are == 'gifter' %}
                            {% if drift.status.value == 1 %}
                                <a href="{{ url_for('main.mailed_drift', did=drift.drift_id) }}">
                                    <span class="btn-normal">已邮寄</span>
                                </a>
                                <a style="margin-top:20px;" href="{{ url_for('main.reject_drift', did=drift.drift_id) }}">
                                    <span class="btn-shadow">拒&nbsp;&nbsp;&nbsp;绝</span>
                                </a>
                            {% endif %}
                        {% endif %}
                        {% if drift.you_are == 'requester' %}
                            {% if drift.status.value == 1 %}
                                <a href="{{ url_for('drift.redraw_drift', drift_id=drift.drift_id) }}">
                                        <span class="btn-normal">撤 销</span>
                                </a>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
                <div style="margin-top:20px;" class="row message-container">
                    <div class="col-md-12">
                        {% if drift.you_are == 'receiver' %}
                            {% set message_flag = '他的留言：' %}
                        {% else %}
                            {% set message_flag = '你的留言：' %}
                        {% endif %}
                        <p><span
                                class="message-flag">{{ message_flag }}</span>
                            <span>{{ drift.message }}</span>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}