app/book/models.py
from sqlalchemy import Column, Integer, String

from app import Model


class Book(Model):
    id = Column(Integer, primary_key=True, autoincrement=True)
    title = Column(String(50), nullable=False)
    author = Column(String(30), default='佚名')
    isbn = Column(String(15), nullable=False, unique=True)
    price = Column(String(20))
    binding = Column(String(20))
    pages = Column(Integer)
    publisher = Column(String(50))
    pubdate = Column(String(20))
    summary = Column(String(1000))
    image = Column(String(50))

app/book/forms.py
from wtforms import Form
from wtforms import StringField, IntegerField
from wtforms.validators import Length, NumberRange, DataRequired


class SearchForm(Form):
    q = StringField(validators=[DataRequired(), Length(min=1, max=30)])
    page = IntegerField(validators=[NumberRange(min=1, max=99)], default=1)

app/book/__init__.py
from flask import Blueprint

book = Blueprint('book', __name__, template_folder='templates')

from . import views
from . import models

app/book/views.py
from flask import request, render_template, flash
from flask_login import current_user

from app.libs.helper import is_isbn_or_key
from app.mian.models import Gift, Wish
from . import book
from .spider import YuShuBook
from .forms import SearchForm
from .viewmodels import Books, Book, TradeInfo


@book.route('/book/search')
def search():
    """
    param:
            q: 关键字 isbn
            page
    """
    form = SearchForm(request.args)
    books = Books()
    if form.validate():
        q = form.q.data.strip()
        page = form.page.data
        isbn_or_key = is_isbn_or_key(q)
        ys_book = YuShuBook()

        if isbn_or_key == 'isbn':
            ys_book.search_by_isbn(q)

        else:
            ys_book.search_by_keyword(q, page)

        books.fill(ys_book, q)
    else:
        flash('搜索的关键字不符合要求，请重新输入')
    return render_template('book/search_result.html', books=books)


@book.route('/book/<isbn>')
def detail(isbn):
    has_in_gifts = False
    has_in_wishes = False

    ys_book = YuShuBook()
    ys_book.search_by_isbn(isbn)
    book_ = Book(ys_book.first)

    if current_user.is_authenticated:
        if Gift.query.filter_by(user_id=current_user.id,
                                isbn=isbn,
                                is_launched=False).first():
            has_in_gifts = True
        if Wish.query.filter_by(user_id=current_user.id,
                                isbn=isbn,
                                is_launched=False).first():
            has_in_wishes = True

    trade_gifts = Gift.query.filter_by(isbn=isbn, is_launched=False).all()
    trade_wishes = Wish.query.filter_by(isbn=isbn, is_launched=False).all()

    gifts = TradeInfo(trade_gifts)
    wishes = TradeInfo(trade_wishes)

    return render_template('book/detail.html',
                           book=book_,
                           wishes=wishes,
                           gifts=gifts,
                           has_in_gifts=has_in_gifts,
                           has_in_wishes=has_in_wishes)

app/book/templates/book/detail.html
{% extends "base.html" %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='3rd/ui/remodal.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='3rd/ui/remodal-default-theme.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/book-detail.css')}}">
{% endblock %}
{% block content %}
    {{ super() }}
    <div class="row book-container">
        <div class="col-md-2">
            <img class="book-img" src="{{ book.image }}"/>
        </div>
        <div style="margin-left: 30px;" class="col-md-5 flex-vertical">
            <div>
                <h4>{{ book.title }}</h4>
            </div>
            <div class="description-font-margin">
                <div>
                    <span>作者:</span>
                    <span>{{ book.author }}</span>
                </div>
                <div>
                    <span>出版社:</span>
                    <span>{{ book.publisher }}</span>
                </div>
                <div>
                    <span>出版年：</span>
                    <span>{{ book.pubdate }}</span>
                </div>
                <div>
                    <span>页数：</span>
                    <span>{{ book.pages }}</span>
                </div>
                <div>
                    <span>定价：</span>
                    <span>{{ book.price }}</span>
                </div>
                <div>
                    <span>精装：</span>
                    <span>{{ book.binding }}</span>
                </div>
                <div>
                    <span>ISBN：</span>
                    <span id="isbn">{{ book.isbn }}</span>
                </div>
                {% if wishes.total or gifts.total %}
                    <div class="color-count">
                        <span>{{ wishes.total }}人想要 / </span>
                        <span>{{ gifts.total}}人可赠送</span>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
    <div style="margin-top:30px;" class="row">
        {% if not has_in_gifts and not has_in_wishes %}
            <div class="col-md-1">
                <a class="btn btn-outline"
                   data-remodal-target="modal">
                    赠送此书
                </a>
            </div>
            <div style="margin-left:30px;" class="col-md-1">
                <a class="btn btn-outline"
                   href="{{ url_for('main.save_to_wish', isbn=book.isbn) }}">
                    加入到心愿清单
                </a>
            </div>
        {% elif has_in_wishes %}
            <div class="col-md-3">
                <span class="bg-info">已添加至心愿清单</span>
            </div>
        {% else %}
            <div class="col-md-3">
                <span class="bg-info">已添加至赠送清单</span>
            </div>
        {% endif %}
    </div>
    <div style="margin-top: 30px;" class="row">
        <div class="col-md-2"><span class="description-title">内容简介</span></div>
    </div>
    <div style="margin-top:15px;" class="row">
        <div class="col-md-11">
            <p class="description-font">{{ book.summary }}</p>
        </div>
    </div>
    {% if gifts.total!= 0 and not has_in_gifts %}
        <div style="margin-top:30px;" class="row">
            <div class="col-md-3"><span class="description-title">向他们请求此书</span></div>
        </div>
        <hr style="margin-top:5px;"/>
        {% for gift in gifts.trades %}
            <div style="margin-top:30px;" class="row">
                <div class="col-md-1">
                    {{ gift.user_name }}
                </div>
                <div class="col-md-2 description-font">
                    上传于{{ gift.time }}
                </div>
                <div class="col-md-2">
                    <a class="btn-normal"
                       href="{{ url_for('drift.send_drift', gift_id=gift.id) }}">向他请求此书</a>
                </div>
            </div>
        {% endfor %}
    {% endif %}
    {% if wishes.total != 0 and has_in_gifts %}
        <div style="margin-top:30px;" class="row">
            <div class="col-md-3"><span class="description-title">向他们赠送此书</span></div>
        </div>
        <hr style="margin-top:5px;"/>
        {% for wish in wishes.trades %}
            <div style="margin-top:30px;" class="row">
                <div class="col-md-1">
                    {{ wish.user_name }}
                </div>
                <div class="col-md-2 description-font">
                    上传于{{ wish.time }}
                </div>
                <div class="col-md-2">
                    <a class="btn-normal"
                       href="{{ url_for('main.satisfy_wish', wish_id=wish.id, isbn=[book.isbn]) }}">向他赠送此书</a>
                </div>
            </div>
        {% endfor %}
    {% endif %}
    <div class="remodal" data-remodal-id="modal" role="dialog"
         aria-labelledby="modal1Title" aria-describedby="modal1Desc"
         data-remodal-options="closeOnOutsideClick: false">
        <button data-remodal-action="close" class="remodal-close"
                aria-label="Close"></button>
        <div>
            <h5 class="diag-title">
                您确定拥有《{{ book.title }}》这本书吗？</h5>
            <p id="modal1Desc" class="description-font">
                如果您不想赠送此书，或者没有这本书，请不要随意发布虚假信息。谢谢你的支持和理解。
            </p>
        </div>
        <br>
        <button data-remodal-action="confirm" class="remodal-confirm">确定赠送</button>
        <button data-remodal-action="cancel" class="remodal-cancel">不，算了</button>
    </div>
{% endblock %}
{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename='3rd/remodal.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/book-detail.js') }}"></script>
{% endblock %}

app/book/templates/book/search_result.html
{% extends "base.html" %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename = 'css/search-result.css')}}">
{% endblock %}
{% block content %}
    {{ super() }}
    <div style="margin-top:20px;" class="row flex-vertical-center">
        <div class="col-md-6">
            <span class="sub-title">搜索 <span class="space highlight"
                                             id="keyword">{{ books.keyword }}</span>的结果</span>
        </div>
        <div class="col-md-3 col-md-offset-3">
            <span class="sub-title"> 共 <span class="space"
                                             id="total">{{ books.total }}</span> 条记录</span>
        </div>
    </div>
    <hr>
    {% for book in books.books %}
        <div class="row col-padding">
            <a href="{{ url_for('book.detail', isbn=book.isbn) }}" class="">
                <div class="col-md-2">
                    <img class="book-img-small shadow" src="{{ book.image }}">
                </div>
                <div class="col-md-7 flex-vertical description-font">
                    <span class="title">{{ book.title }}</span>
{#                    <span>{{ [book.author | d(''), book.publisher | d('', true) , '￥' + book.price | d('')] | join(' / ') }}</span>#}
                    <span>{{book.intro}}</span>
                    <span class="summary">{{ book.summary | default('', true) }}</span>
                </div>
            </a>
        </div>
    {% endfor %}
    <div class="row">
        <div class="flex-hor-center">
            <ul class="pagination" id="pagination"></ul>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename='3rd/jquery.twbsPagination.min.js') }}"></script>
    <script src="{{ url_for('static', filename="js/util.js") }}"></script>
    <script src="{{ url_for('static', filename='js/search_result.js') }}"></script>
{% endblock %}